platform:
  cache:
    type: REDIS
  redis:
    ip: 127.0.0.1
    port: 16379
    password: 'SbtyMveYNfLzTks7H0apCmyStPzWJqjy'
    database: 0

spring:
  cache:
    type: GENERIC
  redis:
    host: ${platform.redis.ip}
    password: ${platform.redis.password}
    port: ${platform.redis.port}
    database: ${platform.redis.database}
